### ISSUE TITLE
If string to output containst multiple words only the first is displayed

### ISSUE THREAD

**Issue by umbundu** [blueimp/JavaScript-Templates#48] opened 2020-04-27 16:33 UTC
Given a string like "this is a great tool",
{%=o.Title%} will display:
This
and ignore the rest!

**Comment by blueimp** [comment] 2020-04-28 18:57
Thanks for your report @umbundu.
Unfortunately I cannot reproduce this issue, e.g. it works as expected on the [demo](https://blueimp.github.io/JavaScript-Templates/).
I'm closing this tentatively, but feel free to provide additional comments with information on how to reproduce your result (e.g. an online demo).

**Closed by blueimp** 2020-04-28 18:57 UTC

**Comment by umbundu** [comment] 2020-04-28 19:14
Sebastian,
How are you? just to thank you for a prompt reply! I do apologize for
opening a ticket without proper testing on my part! I am all set.

Stay safe,
Everardo

**Comment by blueimp** [comment] 2020-04-29 01:07
I'm well, thanks for your kind reply Everardo ☺️
